import { ThemeProvider } from "@/components/theme-provider";
import { supreme } from "@/lib/fonts";
import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { EdgeStoreProvider } from "@/lib/edgestore";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={supreme.className + ' h-screen flex flex-col'}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
      >
          <Navbar />
          <main className=" grow relative">


         <EdgeStoreProvider>{children}</EdgeStoreProvider>
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
